export const ERROR_MESSAGES = {
  sessionRequired: '세션이 만료되었습니다.',
  serverError: '서버에 문제가 발생했습니다.',
  unexpectedError: '알 수 없는 오류가 발생했습니다.',
  invalidCodeError: '유효하지 않은 인증번호입니다.',
};

export const SUCCESS_MESSAGES = {
  loginSuccess: '인증에 성공했습니다.',
  orderCompleteSuccess: '주문이 완료되었습니다.',
  orderCancelSuccess: '주문이 취소되었습니다.',
  orderConfirmSuccess: '송금이 확인되었습니다. 조리를 시작하세요 !',
  orderCookingComplete: '조리가 완료되었습니다. 서빙을 시작하세요 !',
  accountCopySuccess: '계좌번호가 복사되었습니다.',
  waitingSuccess: '손님을 테이블에 안내해주세요 !',
  waitingCancelSuccess: '대기가 취소되었습니다.',
  storeNameUpdateSuccess: '가게 이름이 수정되었습니다.',
  storeAccountUpdateSuccess: '가게 계좌번호가 수정되었습니다.',
  createMenuSuccess: '메뉴가 생성되었습니다.',
  updateMenuSuccess: '메뉴가 수정되었습니다.',
  deleteMenuSuccess: '메뉴가 삭제되었습니다.',
  deleteMenuImageSuccess: '메뉴 이미지가 삭제되었습니다.',
  waitingCreateSuccess: '대기열에 등록되었습니다 !',
  storeNoticeUpdateSuccess: '공지사항이 수정되었습니다.',
  storeEventUpdateSuccess: '이벤트가 수정되었습니다.',
  uploadMenuImageSuccess: '메뉴 이미지가 업로드되었습니다.',
  serviceRequestCancelSuccess: '요청이 취소되었습니다 !',
  serviceRequestSuccess: '요청이 확인되었습니다 !',
  serviceRequestCompleteSuccess: '요청을 처리했습니다 !',
};
